// ============================================================
// Mock data for campaigns & social — used when real API keys
// are not configured. Swap for live API calls in production.
// ============================================================
import type { Campaign, SocialPlatformData } from '~/types'

export const GOOGLE_CAMPAIGNS: Campaign[] = [
  {
    id: 'free-course',
    name: 'Free Grant Writing Course',
    platform: 'google',
    offer: 'Free 5 Key Steps Course',
    goal: 'Email list + course funnel',
    budgetShare: 30,
    color: '#3a7bd5',
    conversion: 'Course Signup',
    spend: 1240,
    leads: 38,
    qualified: 22,
    booked: 9,
    conversions: 38,
    revenue: 3200,
    status: 'active',
    keywords: [
      'free grant writing course',
      'grant writing training',
      'how to write a grant proposal',
      'grant writing for nonprofits',
      'beginner grant writing course',
      'grant writing certificate training',
    ],
  },
  {
    id: 'gw101',
    name: 'Grant Writing 101',
    platform: 'google',
    offer: 'Grant Writing 101: Foundations',
    goal: 'Direct course sales',
    budgetShare: 25,
    color: '#22a053',
    conversion: 'Paid Enrollment',
    spend: 980,
    leads: 21,
    qualified: 14,
    booked: 11,
    conversions: 8,
    revenue: 4800,
    status: 'active',
    keywords: [
      'grant writing course with certificate',
      'online grant writing training',
      'grant writing class for beginners',
      'nonprofit grant writing course',
      'grant proposal writing course',
    ],
  },
  {
    id: 'grants-mgmt',
    name: 'Grants Management Consulting',
    platform: 'google',
    offer: 'Consulting — compliance, reporting, funding readiness',
    goal: 'Consultation requests',
    budgetShare: 30,
    color: '#e8a020',
    conversion: 'Consultation Booking',
    spend: 1340,
    leads: 14,
    qualified: 9,
    booked: 6,
    conversions: 4,
    revenue: 12500,
    status: 'active',
    keywords: [
      'grants management consultant',
      'nonprofit grants management',
      'grant compliance consultant',
      'federal grant management support',
      'grant reporting consultant',
      'grant readiness consultant',
    ],
  },
  {
    id: 'bh-consulting',
    name: 'Behavioral Health Consulting',
    platform: 'google',
    offer: 'BH program development, training, compliance, leadership',
    goal: 'Consulting inquiries',
    budgetShare: 15,
    color: '#7c3aed',
    conversion: 'Consultation Booking',
    spend: 560,
    leads: 8,
    qualified: 5,
    booked: 3,
    conversions: 2,
    revenue: 8000,
    status: 'active',
    keywords: [
      'behavioral health consultant',
      'behavioral health program development',
      'mental health nonprofit consultant',
      'trauma informed care training consultant',
      'crisis intervention training consultant',
      'resilience training for organizations',
    ],
  },
]

export const SOCIAL_PLATFORMS: Record<string, SocialPlatformData> = {
  fb: {
    name: 'Facebook',
    color: '#1877F2',
    bgClass: 'badge-fb',
    icon: 'fb',
    tagline: 'Reach nonprofit leaders, community orgs, and faith-based organizations at scale',
    campaigns: [
      {
        name: 'Nonprofit Audience — Free Course',
        objective: 'Lead Generation',
        audience: 'Nonprofit leaders 35–60 · Interests: grant writing, nonprofit management',
        spend: 620, reach: 14200, clicks: 384, leads: 28, cpl: 22.14,
        conversions: 28, revenue: 1400, adFormat: 'Lead Ad', status: 'active',
        notes: 'Top-of-funnel. Drives free course signups. Feeding GW101 email sequence.',
      },
      {
        name: 'Lookalike Grant Writers — GW101',
        objective: 'Conversions',
        audience: 'Lookalike audience based on existing GW101 buyers · 1% similarity',
        spend: 480, reach: 9800, clicks: 241, leads: 14, cpl: 34.29,
        conversions: 6, revenue: 3582, adFormat: 'Carousel', status: 'active',
        notes: 'Mid-funnel warm audience. Higher CPL but strong course ROAS.',
      },
      {
        name: 'Course Retargeting — GW101',
        objective: 'Retargeting',
        audience: 'Website visitors who viewed /grant-writing-101 · Last 30 days',
        spend: 180, reach: 2100, clicks: 142, leads: 9, cpl: 20.00,
        conversions: 4, revenue: 2388, adFormat: 'Single Image', status: 'active',
        notes: 'Bottom-of-funnel retargeting with discount offer. Best ROAS of all FB campaigns.',
      },
    ],
    audiences: [
      'Nonprofit Executive Directors & Leadership',
      'Program Managers at community-based organizations',
      'Faith-based organization administrators',
      'Small agency owners (1–20 employees)',
      'Development directors and grant coordinators',
      'Lookalike: existing GW101 buyers',
      'Retargeting: landing page visitors',
    ],
    adFormats: ['Lead Ads (free course)', 'Carousel (course benefits)', 'Single Image (retargeting)', 'Video (testimonials)'],
    utm: { source: 'facebook', medium: 'paid_social', click_param: 'fbclid' },
    trackingNote: 'Use Facebook Pixel + Conversions API. Pass fbclid into CRM as click ID.',
    posts: [
      { title: 'Free Course Lead Ad', format: 'Lead Ad', status: 'active', reach: 8400, clicks: 214, leads: 16, date: '2026-05-15' },
      { title: 'GW101 Carousel — 3 Benefits', format: 'Carousel', status: 'active', reach: 5200, clicks: 178, leads: 9, date: '2026-05-20' },
      { title: 'GW101 Retargeting — 30% Off', format: 'Single Image', status: 'active', reach: 1900, clicks: 132, leads: 7, date: '2026-05-22' },
      { title: 'Testimonial Video — Diana O.', format: 'Video', status: 'paused', reach: 3100, clicks: 89, leads: 3, date: '2026-05-10' },
    ],
  },
  ig: {
    name: 'Instagram',
    color: '#E1306C',
    bgClass: 'badge-ig',
    icon: 'ig',
    tagline: 'Visual brand awareness and thought leadership for nonprofit and behavioral health audiences',
    campaigns: [
      {
        name: 'Grant Tips Awareness — Free Course',
        objective: 'Awareness + Traffic',
        audience: 'Nonprofit professionals 28–55 · Interests: grant writing, nonprofit leadership',
        spend: 290, reach: 18600, clicks: 312, leads: 11, cpl: 26.36,
        conversions: 11, revenue: 550, adFormat: 'Reels + Stories', status: 'active',
        notes: 'Top-of-funnel awareness. Short tips reels drive profile visits and course signups.',
      },
      {
        name: 'BH Consulting Awareness',
        objective: 'Awareness + Traffic',
        audience: 'Behavioral health professionals 30–60 · Interests: mental health, nonprofit management',
        spend: 160, reach: 9400, clicks: 148, leads: 5, cpl: 32.00,
        conversions: 2, revenue: 8000, adFormat: 'Stories + Carousels', status: 'active',
        notes: 'Brand awareness for BH consulting. Low volume but high-value leads.',
      },
    ],
    audiences: [
      'Nonprofit professionals (Instagram interest targeting)',
      'Behavioral health service workers',
      'Social work & community service professionals',
      'Followers of nonprofit & grant writing accounts',
      'Retargeting: website visitors from IG traffic',
    ],
    adFormats: ['Reels (60s tips)', 'Stories (swipe-up to course)', 'Carousel (grant tips)', 'Single Image (quote cards)'],
    utm: { source: 'instagram', medium: 'paid_social', click_param: 'fbclid' },
    trackingNote: 'Instagram uses the same Facebook Pixel and fbclid. Run through Meta Ads Manager.',
    posts: [
      { title: '"5 Grant Mistakes" Reel', format: 'Reel', status: 'active', reach: 9200, clicks: 167, leads: 6, date: '2026-05-18' },
      { title: 'Free Course Story — Swipe Up', format: 'Story', status: 'active', reach: 6400, clicks: 112, leads: 4, date: '2026-05-21' },
      { title: 'Grant Writing 101 Carousel', format: 'Carousel', status: 'active', reach: 4800, clicks: 98, leads: 3, date: '2026-05-24' },
      { title: 'BH Consulting Quote Card', format: 'Single Image', status: 'paused', reach: 3100, clicks: 54, leads: 1, date: '2026-05-12' },
    ],
  },
  li: {
    name: 'LinkedIn',
    color: '#0A66C2',
    bgClass: 'badge-li',
    icon: 'li',
    tagline: 'Highest-intent B2B platform for reaching nonprofit decision-makers by job title',
    campaigns: [
      {
        name: 'Nonprofit Leaders — Grants Management',
        objective: 'Lead Generation',
        audience: 'Job Title: Executive Director, CEO, Development Director · Org: Nonprofit · Size: 1–200',
        spend: 780, reach: 8200, clicks: 198, leads: 16, cpl: 48.75,
        conversions: 5, revenue: 18500, adFormat: 'Lead Gen Form', status: 'active',
        notes: 'Highest CPL but highest-value leads. Consulting contract ROAS is exceptional.',
      },
      {
        name: 'Grants Mgmt Professionals — GW101',
        objective: 'Conversions',
        audience: 'Job Title: Grants Manager, Grants Coordinator · Skills: Grant Writing, Nonprofit Mgmt',
        spend: 340, reach: 4800, clicks: 121, leads: 9, cpl: 37.78,
        conversions: 4, revenue: 2388, adFormat: 'Sponsored Content', status: 'active',
        notes: 'Mid-funnel course sale. These leads often upsell to consulting.',
      },
      {
        name: 'BH Agency Leaders — Consulting',
        objective: 'Lead Generation',
        audience: 'Job Title: Clinical Director, VP Programs · Org: Behavioral Health, Human Services',
        spend: 420, reach: 5600, clicks: 134, leads: 8, cpl: 52.50,
        conversions: 2, revenue: 12000, adFormat: 'Lead Gen Form', status: 'active',
        notes: 'Very high-value consulting opportunities. Longer sales cycle.',
      },
    ],
    audiences: [
      'Executive Directors & CEOs of nonprofits',
      'Development Directors & Grant Coordinators',
      'Clinical Directors & Program Directors (BH agencies)',
      'Grants Managers and Compliance Officers',
      'Federal contractors in social services sector',
    ],
    adFormats: ['Lead Gen Forms', 'Sponsored Content (thought leadership)', 'Message Ads', 'Document Ads (free resource)'],
    utm: { source: 'linkedin', medium: 'paid_social', click_param: 'li_fat_id' },
    trackingNote: 'Use LinkedIn Insight Tag. Lead Gen Forms auto-capture contact data — map to CRM via webhook or CSV export.',
    posts: [
      { title: 'Grants Mgmt Consulting Lead Form', format: 'Lead Gen Form', status: 'active', reach: 4100, clicks: 112, leads: 10, date: '2026-05-16' },
      { title: '"5 Signs You Need a Grants Consultant"', format: 'Sponsored Content', status: 'active', reach: 6200, clicks: 178, leads: 7, date: '2026-05-19' },
      { title: 'GW101 Document Ad — Free Chapter', format: 'Document Ad', status: 'active', reach: 3400, clicks: 98, leads: 5, date: '2026-05-23' },
      { title: 'BH Consulting Lead Form', format: 'Lead Gen Form', status: 'active', reach: 3800, clicks: 121, leads: 6, date: '2026-05-26' },
    ],
  },
}

export const MOCK_SEARCH_TERMS = [
  { term: 'free grant writing course', campaign: 'Free Grant Writing Course', platform: 'google', impressions: 1420, clicks: 87, cost: 312, conversions: 32, label: 'keep' },
  { term: 'grant writing training online', campaign: 'Free Grant Writing Course', platform: 'google', impressions: 980, clicks: 54, cost: 196, conversions: 18, label: 'keep' },
  { term: 'grant writer jobs', campaign: 'Free Grant Writing Course', platform: 'google', impressions: 440, clicks: 31, cost: 118, conversions: 0, label: 'negative' },
  { term: 'grant writing course with certificate', campaign: 'Grant Writing 101', platform: 'google', impressions: 760, clicks: 48, cost: 198, conversions: 7, label: 'keep' },
  { term: 'grant writing salary', campaign: 'Grant Writing 101', platform: 'google', impressions: 310, clicks: 22, cost: 89, conversions: 0, label: 'negative' },
  { term: 'grant writing for small nonprofits', campaign: 'Grant Writing 101', platform: 'google', impressions: 890, clicks: 41, cost: 163, conversions: 3, label: 'build_page' },
  { term: 'grants management consultant', campaign: 'Grants Management Consulting', platform: 'google', impressions: 540, clicks: 29, cost: 198, conversions: 4, label: 'keep' },
  { term: 'grant money for individuals', campaign: 'Grants Management Consulting', platform: 'google', impressions: 1200, clicks: 67, cost: 241, conversions: 0, label: 'negative' },
  { term: 'grant readiness assessment for nonprofits', campaign: 'Grants Management Consulting', platform: 'google', impressions: 190, clicks: 9, cost: 72, conversions: 1, label: 'new_campaign' },
  { term: 'behavioral health consultant', campaign: 'Behavioral Health Consulting', platform: 'google', impressions: 320, clicks: 17, cost: 112, conversions: 2, label: 'keep' },
  { term: 'therapist near me', campaign: 'Behavioral Health Consulting', platform: 'google', impressions: 920, clicks: 44, cost: 157, conversions: 0, label: 'negative' },
  { term: 'crisis counseling training', campaign: 'Behavioral Health Consulting', platform: 'google', impressions: 410, clicks: 21, cost: 142, conversions: 1, label: 'watch' },
]
